name: Daily Retrospective

on:
  push:
    branches: [ "master" ]
  schedule:
    - cron: '0 15 * * *'
  workflow_dispatch:

jobs:
  write-retrospective:
    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN_SECRET }}
      GITHUB_USERNAME: ${{ secrets.GITHUB_USERNAME }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
      NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run retrospective script
        run: python main.py
